services:
  sqlserver:
    build:
      context: .
      dockerfile: DB.Dockerfile
    container_name: sqlserver
    hostname: sqlserver
    environment:
      - SA_PASSWORD=P@ssw0rd
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: API.Dockerfile
    container_name: api
    hostname: api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ECommerceDb;User ID=sa;Password=P@ssw0rd;Encrypt=False;Trust Server Certificate=True;
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver

volumes:
  sqlserverdata:
