services:
  sqlserver:
    build:
      context: .
      dockerfile: DB.Dockerfile
    container_name: sqlserver
    hostname: sqlserver
    environment:
      - SA_PASSWORD=P@ssw0rd
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: API.Dockerfile
    container_name: api
    hostname: api
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - USER_SECRETS_ID=83af8e5b-793e-462e-81cc-81b684fdb0a9
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver

volumes:
  sqlserverdata:
